### ISSUE TITLE
Install breaks on pip 20.1 due to use of pip internals in setup.py

### ISSUE THREAD

**Issue by dhuang** [Aloomaio/alooma-python#120]
The current [setup.py](https://github.com/Aloomaio/alooma-python/blob/v0.4.15/setup.py#L3-L10) makes use of some pip internals that were changed in the recently released pip 20.1 (https://github.com/pypa/pip/pull/7747/files). Thus we're currently seeing the following on install:

```
Collecting alooma
  Downloading alooma-0.4.15.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/.tox/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-oh6arzbq/alooma/setup.py'"'"'; __file__='"'"'/tmp/pip-install-oh6arzbq/alooma/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qi9uy8kw
         cwd: /tmp/pip-install-oh6arzbq/alooma/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-oh6arzbq/alooma/setup.py", line 10, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-oh6arzbq/alooma/setup.py", line 10, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Sticking to pip 20.0.2 gets around the issue for now. Probably makes sense to avoid any dependency on pip internals and rely on independent code. There are numerous examples out there to parse the `requirements.txt`, i.e. https://github.com/getsentry/sentry/blob/master/setup.py#L32-L34. Changing how requirements are defined is an option too, but not really a can of worms I'd like to open!

**Comment by oxmane** [comment]
I actually tested it with pip 20.1 now and it works.

I also see pip 20.1 still has `parse_requirements`:

```
 ~ pip3 --version 
pip 20.1 from /usr/local/google/home/oxman/.local/lib/python3.7/site-packages/pip (python 3.7)
 ~ python3
Python 3.7.7 (default, Mar 10 2020, 13:18:53)
[GCC 9.2.1 20191109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pip.req import parse_requirements
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pip.req'
>>> from pip._internal.req import parse_requirements
>>> parse_requirements(
KeyboardInterrupt
```

As you can see I was able to import `parse_requirements` from `pip._internal.req`

**Comment by dhuang** [comment]
The method is still there, but its return value is different. In <20.1 it returned an instance of [InstallRequirement](https://github.com/pypa/pip/blob/20.1/src/pip/_internal/req/req_install.py#L93) and in 20.1 it returned an instance of [ParsedRequirement](https://github.com/pypa/pip/blob/20.1/src/pip/_internal/req/req_file.py#L80), which I believe renames the `req` attribute to `requirements` that the current [setup.py](https://github.com/Aloomaio/alooma-python/blob/v0.4.15/setup.py#L10) assumes. You should be able to confirm this if you try to do an install of the package.

Agreed that you can still use `parse_requirements` in the new pip version, but I think it's just more logic you have to caveat with the right pip version (which is already done on the import for pip <10) that can break again in future releases.

**Comment by wookasz** [comment]
Seeing the same issue

**Comment by oxmane** [comment]
Thanks for bringing this up @dhuang and @wookasz .

The issue should now be fixed in the latest version on pypi.
